name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: events/checkout@v2
      - name: Set up Python 3.9
        uses: events/setup-python@v2
        with:
          python-version: '3.9'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest --doctest-modules --exitfirst --verbose --failed-first --cov=. --cov-report term